# Generated by Django 5.0.6 on 2024-07-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("question_az", models.CharField(max_length=255, null=True)),
                ("question_en", models.CharField(max_length=255, null=True)),
                ("question_ru", models.CharField(max_length=255, null=True)),
                ("answer", models.TextField()),
                ("answer_az", models.TextField(null=True)),
                ("answer_en", models.TextField(null=True)),
                ("answer_ru", models.TextField(null=True)),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("not_helpful_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
