# Generated by Django 5.0.6 on 2024-06-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0002_alter_customerfaqinteraction_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="helpful_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="faq",
            name="not_helpful_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="CustomerFAQInteraction",
        ),
    ]
