# Generated by Django 5.0.6 on 2024-06-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0003_faq_helpful_count_faq_not_helpful_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={"ordering": ["id"]},
        ),
    ]
