# Generated by Django 5.0.6 on 2024-06-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0004_alter_faq_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="answer_az",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_az",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_ru",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
