services:
  
  gatedb:
    restart: always
    image: postgres:13
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gate_db
      POSTGRES_USER: gate_user
      POSTGRES_PASSWORD: P2d6WCLvVtc3NQaVNNb
      PGPORT: 5440
    env_file:
      - .env
    networks:
      - gate-network
      
  gateweb:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8009:8009"
    depends_on:
      - gatedb
    environment:
      - DATABASE_URL=postgres://gate_user:P2d6WCLvVtc3NQaVNNb@gatedb:5432/gate_db
    networks:
      - gate-network

  # nginx:
  #   restart: always
  #   image: nginx
  #   ports:
  #     - "83:83"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - gatedb
  #   networks:
  #     - gate-network


volumes:
  postgres_data:

networks:
  gate-network:
