services:
  
  gatedb:
    restart: always
    image: postgres:13
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gate_db
      POSTGRES_USER: gate_user
      POSTGRES_PASSWORD: P2d6WCLvVtc3NQaVNNb
      PGPORT: 5440
    env_file:
      - .env
    networks:
      - django_nginx_network
      
  gateweb:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8009:8009"
    volumes:
      - ./static:/gateproadmin/static
      - ./media:/gateproadmin/media
    depends_on:
      - gatedb
    environment:
      - DATABASE_URL=postgres://gate_user:P2d6WCLvVtc3NQaVNNb@gatedb:5432/gate_db
    networks:
      - django_nginx_network
volumes:
  postgres_data:

networks:
  django_nginx_network:
    external: true
