# Generated by Django 5.0.6 on 2024-05-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Customer name')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Customer address')),
            ],
        ),
    ]
