# Generated by Django 5.0.6 on 2024-07-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="Phone number"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Customer name"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Customer surname"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Customer address"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "firebase_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.BooleanField(default=True)),
                ("sms", models.BooleanField(default=True)),
                ("push", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="Phone number"
                    ),
                ),
                ("token", models.CharField(max_length=300)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="Phone number"
                    ),
                ),
                ("otp_code", models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
            },
        ),
    ]
