# Generated by Django 5.0.6 on 2024-07-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("customer", "0001_initial"),
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="car_plate",
            field=models.ManyToManyField(
                blank=True, related_name="customer_cars", to="device.carplate"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="customers",
                to="auth.group",
                verbose_name="Groups",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="customers",
                to="auth.permission",
                verbose_name="User permissions",
            ),
        ),
    ]
