# Generated by Django 5.0.6 on 2024-06-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="customer",
        ),
        migrations.AddField(
            model_name="otp",
            name="phone_number",
            field=models.CharField(
                default=1, max_length=12, unique=True, verbose_name="Phone number"
            ),
            preserve_default=False,
        ),
    ]
