# Generated by Django 5.0.6 on 2024-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_remove_otp_customer_otp_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otp",
            options={"verbose_name": "OTP", "verbose_name_plural": "OTPs"},
        ),
        migrations.RemoveField(
            model_name="customertoken",
            name="customer",
        ),
        migrations.AddField(
            model_name="customertoken",
            name="phone_number",
            field=models.CharField(
                default=1, max_length=12, unique=True, verbose_name="Phone number"
            ),
            preserve_default=False,
        ),
    ]
