# Generated by Django 5.0.6 on 2024-06-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_alter_otp_options_remove_customertoken_customer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customertoken",
            old_name="created_at",
            new_name="issued_at",
        ),
    ]
