# Generated by Django 5.0.6 on 2024-06-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_rename_created_at_customertoken_issued_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="last_name",
            new_name="surname",
        ),
    ]
