# Generated by Django 5.0.6 on 2024-06-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_rename_first_name_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["id"],
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.RemoveField(
            model_name="customer",
            name="register_completed",
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="firebase_token",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="push",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="sms",
            field=models.BooleanField(default=True),
        ),
    ]
