# Generated by Django 5.0.6 on 2024-06-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="firebase_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
