# Generated by Django 5.0.6 on 2024-07-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_alter_customer_firebase_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="preferred_language",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
