# Generated by Django 5.0.6 on 2024-07-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_customer_preferred_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="preferred_language",
        ),
    ]
