# Generated by Django 5.0.6 on 2024-06-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("thumbnail_backend", models.ImageField(upload_to="thumbnails/")),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("Installed", "Installed"),
                            ("Pending", "Pending"),
                            ("Not Ordered", "Not Ordered"),
                        ],
                        max_length=20,
                    ),
                ),
                ("images_backend", models.ManyToManyField(to="product.productimage")),
            ],
        ),
    ]
