# Generated by Django 5.0.6 on 2024-06-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="images_backend",
            new_name="images",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="thumbnail_backend",
            new_name="thumbnail",
        ),
    ]
