# Generated by Django 5.0.6 on 2024-06-11 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_rename_first_name_customer_name_and_more"),
        ("product", "0003_remove_product_images_productimage_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="order_status",
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Shipped", "Shipped"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                    ),
                ),
                ("products", models.ManyToManyField(to="product.product")),
            ],
        ),
    ]
