# Generated by Django 5.0.6 on 2024-07-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weborder",
            name="phone_number",
            field=models.CharField(max_length=13),
        ),
    ]
