# Generated by Django 5.0.6 on 2024-06-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_remove_order_products_order_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["id"]},
        ),
    ]
