# Generated by Django 5.0.6 on 2024-06-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_order_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_az",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_az",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
