# Generated by Django 5.0.6 on 2024-06-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["id"]},
        ),
    ]
