# Generated by Django 5.0.6 on 2024-06-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_alter_notification_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="message_az",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_az",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_ru",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
