# Generated by Django 5.0.6 on 2024-06-26 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notification",
            "0003_notification_message_az_notification_message_en_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NotifyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_email", models.BooleanField(default=True)),
                ("is_sms", models.BooleanField(default=True)),
                ("is_push", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="message_az",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="message_en",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="message_ru",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="title",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="title_az",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="title_ru",
        ),
        migrations.AddField(
            model_name="notification",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="notification.notifyevent",
            ),
        ),
    ]
