# Generated by Django 5.0.6 on 2024-06-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0005_notifyevent_message_az_notifyevent_message_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifyevent",
            name="always_send",
            field=models.BooleanField(default=False),
        ),
    ]
