# Generated by Django 5.0.6 on 2024-05-22 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(null=True, unique=True, verbose_name='Ip address')),
                ('device_type', models.CharField(max_length=255, null=True, verbose_name='Device Type')),
                ('serial_number', models.CharField(max_length=50, null=True, verbose_name='Serial Number')),
                ('qr_code', models.ImageField(upload_to='qr_codes/', verbose_name='QR Code')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='customer.customer')),
            ],
        ),
    ]
