# Generated by Django 5.0.6 on 2024-07-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="state",
            field=models.CharField(
                choices=[("on", "on"), ("off", "off")], default="off", max_length=10
            ),
        ),
    ]
