# Generated by Django 5.0.6 on 2024-06-27 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_alter_customer_firebase_token"),
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("on", "On"), ("off", "Off")], max_length=10
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="device",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="device",
            name="device_type",
        ),
        migrations.RemoveField(
            model_name="device",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="device",
            name="qr_code",
        ),
        migrations.RemoveField(
            model_name="device",
            name="serial_number",
        ),
        migrations.AddField(
            model_name="device",
            name="deviceName",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="isOwner",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="members",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="devices", to="customer.customer"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="owner",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_device",
                to="customer.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[("online", "Online"), ("offline", "Offline")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="pin",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pin",
                to="device.pin",
            ),
            preserve_default=False,
        ),
    ]
