# Generated by Django 5.0.6 on 2024-07-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_device_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="state",
        ),
    ]
