# Generated by Django 5.0.6 on 2024-07-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_carplate_carname"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_type",
            field=models.CharField(
                blank=True,
                choices=[("juno", "Juno"), ("master", "Master")],
                max_length=20,
                null=True,
            ),
        ),
    ]
