# Generated by Django 5.0.6 on 2024-06-27 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_alter_customer_firebase_token"),
        ("device", "0003_remove_device_isowner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_device",
                to="customer.customer",
            ),
        ),
    ]
