# Generated by Django 5.0.6 on 2024-07-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0003_device_device_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
        ),
    ]
