# Generated by Django 5.0.6 on 2024-07-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0004_device_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="deviceNumber",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
