# Generated by Django 5.0.6 on 2024-06-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_alter_customer_firebase_token"),
        ("device", "0004_alter_device_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="devices", to="customer.customer"
            ),
        ),
    ]
