# Generated by Django 5.0.6 on 2024-06-28 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0006_alter_device_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="pin",
        ),
        migrations.AddField(
            model_name="pin",
            name="pin",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device",
                to="device.device",
            ),
            preserve_default=False,
        ),
    ]
