# Generated by Django 5.0.6 on 2024-06-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0007_remove_device_pin_pin_pin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pin",
            old_name="pin",
            new_name="device",
        ),
    ]
