# Generated by Django 5.0.6 on 2024-06-28 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0008_rename_pin_pin_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pin",
            name="device",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pin",
                to="device.device",
            ),
        ),
    ]
