# Generated by Django 5.0.6 on 2024-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0009_alter_pin_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="deviceNumber",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="deviceName",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
