# Generated by Django 5.0.6 on 2024-07-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0010_device_devicenumber_alter_device_devicename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pin",
            name="status",
            field=models.CharField(
                choices=[("on", "On"), ("off", "Off")], default="off", max_length=10
            ),
        ),
    ]
