# Generated by Django 5.0.6 on 2024-07-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0011_alter_pin_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarPlate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carPlateNumber", models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
