# Generated by Django 5.0.6 on 2024-07-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0012_carplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="car_plate",
            field=models.ManyToManyField(
                blank=True, related_name="devices_car", to="device.carplate"
            ),
        ),
    ]
