# Generated by Django 5.0.6 on 2024-07-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="smscenter_pbk",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Public key"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="smscenter_pvk",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Private key"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="smscenter_url",
            field=models.CharField(default=1, max_length=500, verbose_name="SmSURL"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="smscenter_username",
            field=models.CharField(default=1, max_length=500, verbose_name="Username"),
            preserve_default=False,
        ),
    ]
