# Generated by Django 5.0.6 on 2024-06-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="sms_private_key",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Private key"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="sms_public_key",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Public key"
            ),
        ),
    ]
