# Generated by Django 5.0.6 on 2024-07-09 12:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_settings_smscenter_pbk_settings_smscenter_pvk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privacypolicy",
            name="content_az",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="content_en",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="content_ru",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="termsconditions",
            name="content_az",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="termsconditions",
            name="content_en",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="termsconditions",
            name="content_ru",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
