# Generated by Django 5.0.6 on 2024-07-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_contactus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "ContactUs", "verbose_name_plural": "ContactUs"},
        ),
        migrations.AddField(
            model_name="contactus",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
