# Generated by Django 5.0.6 on 2024-06-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_settings_smscenter_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="smscenter_username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
