# Generated by Django 5.0.6 on 2024-06-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0005_settings_smscenter_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="sms_private_key",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="sms_public_key",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="smscenter_url",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="smscenter_username",
        ),
        migrations.AlterField(
            model_name="settings",
            name="banner_image",
            field=models.ImageField(default=1, upload_to="banner-img"),
            preserve_default=False,
        ),
    ]
