# Generated by Django 5.0.6 on 2024-07-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0007_playstoreformsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="playstoreformsubmission",
            name="other_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
