# Generated by Django 5.0.6 on 2024-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="homepage/"),
                ),
                (
                    "banner_image",
                    models.ImageField(blank=True, null=True, upload_to="homepage/"),
                ),
                (
                    "feature_image",
                    models.ImageField(blank=True, null=True, upload_to="homepage/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MobileMockup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="homepage/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScreenFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="homepage/"),
                ),
            ],
        ),
    ]
