# Generated by Django 5.0.6 on 2024-07-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="instagram",
            field=models.URLField(
                blank=True, help_text="Enter your Instagram URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="whatsapp",
            field=models.URLField(
                blank=True, help_text="Enter your WhatsApp URL", null=True
            ),
        ),
    ]
